//DOM elements
export const elements = {
    buttonBox: document.getElementById('button__box'),
    boxMiddle: document.querySelector('.box__middle'),
    dateInput: document.getElementById('date__input'),
    expenseAmount: document.getElementById('expense__amount'),
    expenseDescription: document.getElementById('expense__description'),
    expenseBtn: document.getElementById('expense__btn'),
    eventBtn: document.getElementById('event__btn'),
    eventMenu: document.querySelector('.event__menu'),
    eventMenuCloseBtn: document.getElementById('event__menu__close__btn'),
    eventName: document.querySelector('#event__name'),
    eventSelector: document.querySelector('.event__selector'),
    menuBtn: document.querySelector('.fa-bars'),
    nameInput: document.getElementById('name__input'),
    peopleList: document.getElementById('people__list'),
    personBtn: document.getElementById('person__btn'),
    personCont: document.querySelector('.person__container'),
    personMenu: document.querySelector('.person__menu'),
    personMenuCloseBtn: document.getElementById('person__menu__close__btn'),
    personMenuOpenBtn: document.querySelector('.person__menu__open__btn'),
    personName: document.getElementById('person__name'),
};